"use strict";

document.getElementById("create_docreate").addEventListener("click", onDoCreate);
document.getElementById("create_doabort").addEventListener("click", onDoAbort);
document.getElementById("create_generate").addEventListener("change", onGenerateCheckboxChange);

function createNewDialog(event) {
    document.getElementsByClassName('search')[0].style.display = 'none';
    document.getElementsByClassName('results')[0].style.display = 'none';
    document.getElementsByClassName('create')[0].style.display = 'block';
    document.getElementById('create_name').value = [options['defaultfolder'], urlDomain(currentTab.url)].join('/');
}

function switchToSearch() {
    document.getElementsByClassName('search')[0].style.display = 'block';
    document.getElementsByClassName('results')[0].style.display = 'block';
    document.getElementsByClassName('create')[0].style.display = 'none';
}

function onDoCreate(event) {
    event.preventDefault();
    var entryName = document.getElementById("create_name").value,
        login = document.getElementById("create_login").value,
        password = document.getElementById("create_password").value,
        generate = document.getElementById(("create_generate")).checked,
        passwordLength = Number(document.getElementById(("create_generate_length")).value),
        useSymbols = document.getElementById(("create_use_symbols")).checked;
    console.log('creating secret', entryName);
    var message = {
        type: "create",
        entry_name: entryName,
        login: login,
        password: password,
        length: passwordLength,
        generate: generate,
        use_symbols: useSymbols
    };
    sendNativeMessage(message, onCreateResult, onCreateError);
}

function onDoAbort(event) {
    switchToSearch();
}

function onGenerateCheckboxChange(event) {
    var password = document.getElementById('create_password');
    if (event.target.checked) {
        password.value = '';
        password.placeholder = 'will be autogenerated';
    } else {
        password.placeholder = 'type password here';
    }
    password.disabled = event.target.checked;
    document.getElementById('create_generate_length').disabled = !event.target.checked;
    document.getElementById('create_use_symbols').disabled = !event.target.checked;
}

function onCreateResult(response) {
    switchToSearch();
    if (response.error) {
        setStatusText(response.error);
        return;
    }
    console.log("created");
    searchTerm = urlDomain(currentTab.url);
    searchHost(searchTerm);
}

function onCreateError(error) {
    console.log(error);
    switchToSearch();
    setStatusText(error.message);
}
